version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: copy-in-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gpadmin
      POSTGRES_PASSWORD: gpadmin
      POSTGRES_DB: gpadmin

  greenplum:
    cap_add:
      - SYS_RESOURCE
    container_name: greenplum
    image: 'projectairws/greenplum:latest'
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "5432:5432"
    restart: unless-stopped
    tty: true
